### ISSUE TITLE
clang hasn't been updated in 5 days!

### ISSUE THREAD

**Issue by nickdesaulniers** [ClangBuiltLinux/continuous-integration2#384] opened 2022-07-03 02:28 UTC
https://github.com/ClangBuiltLinux/continuous-integration2/runs/7165582834?check_suite_focus=true

sounds like there's a hiccup in the CI

cc @sylvestre in case this is not a known issue.

**Comment by nathanchance** [comment] 2022-07-04 19:38
It looks like neither the Bullseye nor Sid builds of LLVM have been updated in July.

**Comment by sylvestre** [comment] 2022-07-04 21:01
Yeah, it was blocked by https://reviews.llvm.org/D107082#3626632
I worked on it during the week end and i just re triggered a compilation for bullseye

Debian sid is broken because of https://bugs.debian.org/1014114
```

"/build/llvm-toolchain-snapshot-15~++20220704111934+740633ff08ff/build-llvm/./bin/clang++" --target=x86_64-pc-linux-gnu -DHAVE_RPC_XDR_H=0 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I"/build/llvm-toolchain-snapshot-15~++20220704111934+740633ff08ff/compiler-rt/lib/sanitizer_common/.." -I"/build/llvm-toolchain-snapshot-15~++20220704111934+740633ff08ff/build-llvm/include" -fstack-protector-strong -Wformat -Werror=format-security -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -ffile-prefix-map=/build/llvm-toolchain-snapshot-15~++20220704111934+740633ff08ff/build-llvm/runtimes/runtimes-bins=build-llvm/runtimes/runtimes-bins -ffile-prefix-map=/build/llvm-toolchain-snapshot-15~++20220704111934+740633ff08ff/= -no-canonical-prefixes -Wall -std=c++14 -Wno-unused-parameter -O3 -DNDEBUG -m32 -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fno-sanitize=safe-stack -fvisibility=hidden -fno-lto -Wthread-safety -Wthread-safety-reference -Wthread-safety-beta -O3 -gline-tables-only -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions -nostdinc++ -Wno-format -fno-rtti -Wframe-larger-than=570 -Wglobal-constructors -MD -MT compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.i386.dir/sanitizer_platform_limits_posix.cpp.o -MF compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.i386.dir/sanitizer_platform_limits_posix.cpp.o.d -o compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.i386.dir/sanitizer_platform_limits_posix.cpp.o -c '/build/llvm-toolchain-snapshot-15~++20220704111934+740633ff08ff/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp'
/build/llvm-toolchain-snapshot-15~++20220704111934+740633ff08ff/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp:178:10: fatal error: 'crypt.h' file not found
#include <crypt.h>
         ^~~~~~~~~
1 error generated.
```

**Comment by nathanchance** [comment] 2022-07-13 21:35
Looks like this is a problem again:

https://github.com/ClangBuiltLinux/continuous-integration2/actions/runs/2660384158

Our PowerPC builds are red due to an LLVM regression so updating would help resolve that:

https://reviews.llvm.org/D125990#3633683

https://reviews.llvm.org/rG58b9666dc1a09819377ae585b4718ef2ea951970

**Comment by sylvestre** [comment] 2022-07-14 16:04
on the debian side, I think both are fixed now

**Closed** 2022-07-14 16:06 UTC
