### ISSUE TITLE
Handle LLVM 12 to LLVM 13 transition

### ISSUE THREAD

**Issue by nathanchance** [ClangBuiltLinux/continuous-integration2#62] opened 2021-01-28 20:16 UTC
- [x] Wait for LLVM 12 binaries on [apt.llvm.org](https://apt.llvm.org/)
- [x] Report availability of LLVM 12 binaries on [apt.llvm.org](https://apt.llvm.org/) to [TuxMake issue tracker](https://gitlab.com/Linaro/tuxmake): https://gitlab.com/Linaro/tuxmake/-/issues/119
- [x] Wait for TuxMake to provide `clang-12` images: https://gitlab.com/Linaro/tuxmake/-/merge_requests/103
- [x] Wait for TuxSuite to allow `clang-12` to be specified: https://gitlab.com/Linaro/tuxsuite/-/issues/98
- [ ] Update `generator.yml` to provide `llvm_11` anchor, shift `llvm_latest` to 12, and shift `llvm_tot` to 13

Just a heads up @DanRue

**Comment by danrue** [comment] 2021-01-29 20:54
cc @terceiro

**Comment by nickdesaulniers** [comment] 2021-01-30 06:36
cc @sylvestre

**Comment by dileks** [comment] 2021-02-01 01:43
On Sat, Jan 30, 2021 at 7:37 AM Nick Desaulniers <notifications@github.com>
wrote:

> cc @sylvestre <https://github.com/sylvestre>
>

llvm-toolchain-12 and llvm-toolchain fired up...

# LC_ALL=C apt-cache policy clang-12

clang-12:
 Installed: 1:12.0.0~++20210131094231+07dc51637cc4-1~exp1~20210131084941.4
 Candidate: 1:12.0.0~++20210131094231+07dc51637cc4-1~exp1~20210131084941.4
 Version table:
*** 1:12.0.0~++20210131094231+07dc51637cc4-1~exp1~20210131084941.4 100
        99 https://apt.llvm.org/unstable llvm-toolchain-12/main amd64
Packages
       100 /var/lib/dpkg/status
    1:12~++20201105093023+cc2a2bb5ce5-1~exp1 99
        99 http://ftp.debian.org/debian experimental/main amd64 Packages
        99 https://deb.debian.org/debian experimental/main amd64 Packages

# LC_ALL=C apt-cache policy clang-13
clang-13:
 Installed: (none)
 Candidate: 1:13~++20210131111112+be997cead7fa-1~exp1~20210131101819.3757
 Version table:
    1:13~++20210131111112+be997cead7fa-1~exp1~20210131101819.3757 99
        99 https://apt.llvm.org/unstable llvm-toolchain/main amd64 Packages
    1:13~++20210129063721+010b176cdefb-1~exp1 99
        99 https://incoming.debian.org/debian-buildd
buildd-experimental/main amd64 Packages
        99 http://ftp.debian.org/debian experimental/main amd64 Packages
        99 https://deb.debian.org/debian experimental/main amd64 Packages

- sed@ -

>

**Comment by sylvestre** [comment] 2021-02-01 11:56
Yeah, live already, did that this week end :)

**Comment by dileks** [comment] 2021-02-01 15:02
@sylvestre 

Thanks for your work.

Can we have a version `12.0.0-rc1` in Debian/experimental?

**Comment by sylvestre** [comment] 2021-02-01 15:10
No, it is still in NEW https://ftp-master.debian.org/new.html
I will ping ftpmaster

**Comment by sylvestre** [comment] 2021-02-02 09:07
@dileks 
`llvm-toolchain-12_12.0.0~+rc1-1~exp1_amd64.changes ACCEPTED into experimental, experimental`
It has been accepted a few minutes ago
https://tracker.debian.org/pkg/llvm-toolchain-12

**Comment by dileks** [comment] 2021-02-02 09:34
Thanks.

Sylvestre Ledru <notifications@github.com> schrieb am Di., 2. Feb. 2021,
10:07:

**Comment by terceiro** [comment] 2021-02-02 17:48
hello @sylvestre :-) is it normal  for `clang-12` to have disappeared from `deb http://apt.llvm.org/unstable/ llvm-toolchain main`? the `clang` from there is now uninstallable on a clean system due to this.

**Comment by sylvestre** [comment] 2021-02-02 17:51
Yeah, use
```

deb http://apt.llvm.org/unstable/ llvm-toolchain-12 main
deb-src http://apt.llvm.org/unstable/ llvm-toolchain-12 main
```

**Comment by sylvestre** [comment] 2021-02-02 17:58
I updated https://apt.llvm.org/ (wait until the CDN is refreshed)

**Comment by terceiro** [comment] 2021-02-02 19:48
I don't need clang-12 specifically, I just need the *latest* clang from the "llvm-toolchain" repo to be installable. i.e. today `clang` from "llvm-toolchain" depends on clang-12, but only clang-13 is provided in that same repo.

**Comment by sylvestre** [comment] 2021-02-03 10:18
Oh, that, ok :)
I think it should be fixed now too

**Comment by nickdesaulniers** [comment] 2021-02-03 18:46
Right, now that release/12.x exists, we'd like to test clang-10, clang-11, clang-12pre, and clang-13pre.  ('pre' meaning both branches are still moving forward in time, but are divergent.  We'd like to be to test both to prevent regressions from shipping once released formally).

**Closed** 2021-02-10 19:01 UTC
Labels: tuxsuite / tuxmake
